const Types = {
  AUTENTICATION: 'spotify/AUTENTICATION',
  AUTENTICATION_CONCLUDED: 'spotify/AUTENTICATION_CONCLUDED',
  AUTENTICATION_ERROR: 'spotify/AUTENTICATION_ERROR',
  SEARCH_API: 'spotify/SEARCH_API',
  SEARCH_API_CONCLUDED: 'spotify/SEARCH_API_CONCLUDED',
  SEARCH_API_ERROR: 'spotify/SEARCH_API_ERROR',
  GET_ALBUM_INFO: 'spotify/GET_ALBUM_INFO',
  GET_ALBUM_INFO_CONCLUDED: 'spotify/GET_ALBUM_INFO_CONCLUDED',
  GET_ALBUM_INFO_ERROR: 'spotify/GET_ALBUM_INFO_ERROR',
};

export default Types;
